# Generated by Django 4.1.4 on 2023-04-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newmodel',
            table='my new table for database',
        ),
    ]
