# Generated by Django 4.1.4 on 2023-05-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_newmodel_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newModel',
            new_name='nameModel',
        ),
    ]
