# Generated by Django 4.1.4 on 2023-05-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_rename_newmodel_namemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nameModel',
        ),
    ]
